services:
  - type: web
    name: ai-contract-review
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: NOTIFICATION_WEBHOOK_URL
        sync: false